-
    question: "Which of the following constants do not exist ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/console/blob/6.0/Input/InputArgument.php#L24-L26
        - https://symfony.com/doc/6.0/console/input.html#using-command-arguments
    answers:
        - {value: "Symfony\\Component\\Console\\Input\\InputArgument::NONE", correct: true}
        - {value: "Symfony\\Component\\Console\\Input\\InputArgument::NEGATABLE", correct: true}
        - {value: "Symfony\\Component\\Console\\Input\\InputArgument::REQUIRED", correct: false}
        - {value: "Symfony\\Component\\Console\\Input\\InputArgument::IS_ARRAY", correct: false}
        - {value: "Symfony\\Component\\Console\\Input\\InputArgument::OPTIONAL", correct: false}
-
    question: "Given the context where <info>COLUMNS</info> is set as en environment variable with the value of <info>120</info>, what will be the value returned using the following code ?"
    code_snippet: |
        <?php

        use Symfony\Component\Console\Terminal;

        echo (new Terminal())->getWidth();
    correction_help:
        - https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Console/Terminal.php
    answers:
        - {value: "An error", correct: false}
        - {value: "The integer <info>0</info>", correct: false}
        - {value: "The integer <info>120</info>", correct: true}
        - {value: "The width of the actual terminal if used in the context of a terminal", correct: false}
        - {value: "The integer <info>200</info>", correct: false}
        - {value: "Nothing", correct: false}
        - {value: "The integer <info>80</info>", correct: false}
-
    question: "Could <info>Command</info> be use as a concrete class without defining the <info>execute</info> method ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Console/Command/Command.php#L145
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Console/Command/Command.php#L194
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "Could commands be executed via the messages bus ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/blog/new-in-symfony-6-4-more-built-in-message-handlers#run-command-handler
        - https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Console/Messenger/RunCommandMessage.php
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "What is the return type of the <info>Symfony\\Component\\Console\\Command::execute</info> method ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/6.0/console.html#creating-a-command
        - https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/Console/Command/Command.php#L293-L295
    answers:
        - {value: "?bool", correct: false}
        - {value: "?int", correct: false}
        - {value: "int", correct: true}
        - {value: "bool", correct: false}
        - {value: "void", correct: false}
