-
    question: "Could the environment variables be debugged ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/blog/new-in-symfony-5-4-misc-features-part-2#new-command-to-debug-environment-variables
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}