-
    question: "Which of the following are Filesystem methods ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/components/filesystem/introduction.html#usage
    answers:
        - {value: "mirror", correct: true}
        - {value: "copy", correct: true}
        - {value: "delete", correct: false}
        - {value: "chown", correct: true}
        - {value: "move", correct: false}
        - {value: "makePathRelative", correct: true}
        - {value: "symlink", correct: true}
-
    question: "Could paths be manipulated using a Symfony API ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/5.4/components/filesystem.html#path-manipulation-utilities
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "Given the following code snippet, what will be displayed ?"
    code_snippet: |
        <?php

        use Symfony\Component\Filesystem\Path;

        echo Path::getRoot("/etc/apache2/sites-available");
    correction_help:
        - https://symfony.com/doc/5.4/components/filesystem.html#finding-directories-root-directories
        - https://github.com/symfony/filesystem/blob/5.4/Path.php#L207
    answers:
        - {value: "/", correct: true}
        - {value: "/etc/apache2/", correct: false}
        - {value: "/etc/", correct: false}
        - {value: "/etc", correct: false}
        - {value: "/etc/apache2", correct: false}
        - {value: "/etc/apache2/sites-available", correct: false}
-
    question: "Which method can be used to copy a whole directory to a new one ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/2.1/components/filesystem.html#mirror
    answers:
        - {value: "It's not possible", correct: false}
        - {value: "<info>mirror</info>", correct: true}
        - {value: "<info>symlink</info>", correct: false}
        - {value: "<info>copy</info>", correct: false}