-
    question: "Which of the following are Filesystem methods ?"
    code_snippet: ~
    correction_help:
        - http://symfony.com/doc/current/components/filesystem/introduction.html#usage
    answers:
        - {value: "mirror", correct: true, code_snippet: false}
        - {value: "copy", correct: true, code_snippet: false}
        - {value: "delete", correct: false, code_snippet: false}
        - {value: "chown", correct: true, code_snippet: false}
        - {value: "move", correct: false, code_snippet: false}
        - {value: "makePathRelative", correct: true, code_snippet: false}
        - {value: "symlink", correct: true, code_snippet: false}
-
    question: "Could paths be manipulated using a Symfony API ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/5.4/components/filesystem.html#path-manipulation-utilities
    answers:
        - {value: "Yes", correct: true, code_snippet: false}
        - {value: "No", correct: false, code_snippet: false}