-
    question: "How to add an extension <info>MyForm</info> to the <info>Form</info> component ?"
    code_snippet: ~
    correction_help:
        - https://...
    answers:
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->addExtension('text', new MyFormExtension())
                  ->getFormFactory();
          correct: false
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->add(new MyFormExtension())
                  ->getFormFactory();
          correct: false
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->addExtension(new MyFormExtension())
                  ->getFormFactory();
          correct: true
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->registerExtension(new MyFormExtension())
                  ->getFormFactory();
          correct: false
-
    question: "Is <info>Symfony\\Component\\Form\\Form::isValid()<info> the method responsible for validating its data ?"
    code_snippet: ~
    correction_help:
        - "<info>ValidationListener</info> actually do the job"
        - https://github.com/symfony/symfony/blob/0baa58d4e4bb006c4ae68f75833b586bd3cb6e6f/src/Symfony/Component/Form/Form.php#L744
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php
    answers:
        - {value: "Yes", correct: false}
        - {value: "No", correct: true}
-
    question: "Could a <info>Button</info> have a child ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/ButtonBuilder.php#L84
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/Button.php#L120
    answers:
        - {value: "Yes", correct: false}
        - {value: "No", correct: true}
-
    question: "What solution can you use to ask the user to type his password twice in a form ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/reference/forms/types/repeated.html
    answers:
        - {value: "Use the <info>RepeatedType</info> form type", correct: true}
        - {value: "Use the validation plugin of jQuery", correct: false}
        - {value: "Use the <info>ask_confirmation</info> option on the <info>PasswordType</info> form type", correct: false}
        - {value: "Call the <info>render_widget</info> twig function twice on the password form field", correct: false}
-
    question: "Given a form where the <info>inherit_data</info> option is set to <info>true</info> in the form options, which event listeners this form will have access ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/form/inherit_data_option.html
    answers:
        - {value: "PRE_SET_DATA", correct: false}
        - {value: "POST_SET_DATA", correct: false}
        - {value: "PRE_SUBMIT", correct: true}
        - {value: "SUBMIT", correct: true}
        - {value: "POST_SUBMIT", correct: true}
