-
    question: "How to add an extension <info>MyForm</info> to the <info>Form</info> component ?"
    code_snippet: ~
    correction_help:
        - https://...
    answers:
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->addExtension('text', new MyFormExtension())
                  ->getFormFactory();
          correct: false
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->add(new MyFormExtension())
                  ->getFormFactory();
          correct: false
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->addExtension(new MyFormExtension())
                  ->getFormFactory();
          correct: true
        - value: |
              $formFactory = Forms::createFormFactoryBuilder()
                  ->registerExtension(new MyFormExtension())
                  ->getFormFactory();
          correct: false
-
    question: "Is <info>Symfony\\Component\\Form\\Form::isValid()</info> the method responsible for validating its data ?"
    code_snippet: ~
    correction_help:
        - "ValidationListener actually do the job"
        - https://github.com/symfony/symfony/blob/0baa58d4e4bb006c4ae68f75833b586bd3cb6e6f/src/Symfony/Component/Form/Form.php#L744
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php
    answers:
        - {value: "Yes", correct: false}
        - {value: "No", correct: true}
-
    question: "Could a <info>Button</info> have a child ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/ButtonBuilder.php#L84
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Form/Button.php#L120
    answers:
        - {value: "Yes", correct: false}
        - {value: "No", correct: true}
-
    question: "What solution can you use to ask the user to type his password twice in a form ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/reference/forms/types/repeated.html
    answers:
        - {value: "Use the <info>RepeatedType</info> form type", correct: true}
        - {value: "Use the validation plugin of jQuery", correct: false}
        - {value: "Use the <info>ask_confirmation</info> option on the <info>PasswordType</info> form type", correct: false}
        - {value: "Call the <info>render_widget</info> twig function twice on the password form field", correct: false}
-
    question: "Given a form where the <info>inherit_data</info> option is set to <info>true</info> in the form options, which event listeners this form will have access ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/form/inherit_data_option.html
    answers:
        - {value: "<info>PRE_SET_DATA</info>", correct: false}
        - {value: "<info>POST_SET_DATA</info>", correct: false}
        - {value: "<info>PRE_SUBMIT</info>", correct: true}
        - {value: "<info>SUBMIT</info>", correct: true}
        - {value: "<info>POST_SUBMIT</info>", correct: true}
-
    question: "How to get the value set for the field <info>title</info> in a form ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/3.0/reference/forms/twig_reference.html#form-variables-reference
    answers:
        - {value: "<info>{{ form.vars.title.value }}</info>", correct: false}
        - {value: "<info>{{ form.vars.title }}</info>", correct: false}
        - {value: "<info>{{ form.title.vars.value }}</info>", correct: true}
        - {value: "<info>{{ form.title }}</info>", correct: false}
-
    question: "Is there a way to make sure the <info>{{ form_end(form) }}</info> does not render the fields who have not been rendered previously ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/reference/forms/twig_reference.html#form-end-view-variables
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "Which of the following are Symfony built-in field types ?"
    code_snippet: ~
    correction_help:
        - http://symfony.com/doc/current/reference/forms/types.html#supported-field-types
    answers:
        - {value: "<info>IntervalType</info>", correct: false}
        - {value: "<info>NumberType</info>", correct: true}
        - {value: "<info>PercentType</info>", correct: true}
        - {value: "<info>RangeType</info>", correct: true}
        - {value: "<info>IntegerType</info>", correct: true}
        - {value: "<info>MoneyType</info>", correct: true}
        - {value: "<info>DecimalType</info>", correct: false}
-
    question: "Assuming an application that stores money amounts multiplied by 100 (e.g. 1.23 is stored as 123), what option is needed to be set to display the value correctly to the user ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/2.3/reference/forms/types/money.html
    answers:
        - {value: "<info>scale</info>", correct: false}
        - {value: "<info>divisor</info>", correct: true}
        - {value: "<info>by_reference</info>", correct: false}
        - {value: "<info>multiply</info>", correct: false}