-
    question: "For a request to <info>https://example.com/blog/index.php/post/hello-world</info>, what will be the value of <info>$pathInfo</info> in the following code ?"
    code_snippet: "$pathInfo = $request->getPathInfo();"
    correction_help:
        - https://symfony.com/doc/current/components/http_foundation.html#identifying-a-request
    answers:
        - {value: "/index.php/post/hello-world", correct: false}
        - {value: "/blog/index.php/post/hello-world", correct: false}
        - {value: "/post/hello-world", correct: true}
        - {value: "example.com/blog/index.php/post/hello-world", correct: false}
-
    question: "How could you simulate a GET request to <info>/hello-world</info> ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/components/http_foundation.html#identifying-a-request
    answers:
        - {value: "$request = Request::create(null, '/hello-world');", correct: false, code_snippet: true}
        - {value: "$request = Request::create('/hello-world', 'GET');", correct: true, code_snippet: true}
        - {value: "$request = Request::create('GET', '/hello-world');", correct: false, code_snippet: true}
        - {value: "$request = Request::create('/hello-world');", correct: true, code_snippet: true}
-
    question: "Which of the following are valid Symfony responses classes extending the base <info>Symfony\\Component\\HttpFoundation\\Response</info> class ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/components/http_foundation/introduction.html#redirecting-the-user
        - https://symfony.com/doc/current/components/http_foundation/introduction.html#streaming-a-response
        - https://symfony.com/doc/current/components/http_foundation/introduction.html#serving-files
        - https://symfony.com/doc/current/components/http_foundation/introduction.html#creating-a-json-response
    answers:
        - {value: "FileResponse", correct: false, code_snippet: false}
        - {value: "BinaryFileResponse", correct: true, code_snippet: false}
        - {value: "StreamedResponse", correct: true, code_snippet: false}
        - {value: "BinaryResponse", correct: false, code_snippet: false}
        - {value: "StreamResponse", correct: false, code_snippet: false}
        - {value: "ImageResponse", correct: false, code_snippet: false}
        - {value: "RedirectedResponse", correct: false, code_snippet: false}
        - {value: "RedirectResponse", correct: true, code_snippet: false}
        - {value: "NotFoundResponse", correct: false, code_snippet: false}
        - {value: "ImageFileResponse", correct: false, code_snippet: false}
        - {value: "JsonResponse", correct: true, code_snippet: false}
-
    question: "Is it possible to change the status code of a <info>Symfony\\Component\\HttpFoundation\\Response</info> ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/components/http_foundation.html#response
    answers:
        - {value: "No", correct: false, code_snippet: false}
        - {value: "Yes, with the <info>setStatusCode()</info> method", correct: true}
        - {value: "Yes, with the <info>setCode()</info> method", correct: false}
        - {value: "Yes, with the <info>setStatus()</info> method", correct: false}
-
    question: "Could the <info>FlashBag</info> messages be retrieved without being removed from the bag ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.1/src/Symfony/Component/HttpFoundation/Session/Flash/FlashBag.php
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "What kernel event is dispatched when a controller does not return a <info>Response</info> object ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/5.x/reference/events.html
    answers:
        - {value: "kernel.terminate", correct: false}
        - {value: "kernel.finish_request", correct: false}
        - {value: "kernel.view", correct: true}
        - {value: "kernel.response", correct: false}
-
    question: "Which statement is true about <info>FlashBag::add()</info> and <info>FlashBag::set()</info> ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.1/src/Symfony/Component/HttpFoundation/Session/Flash/FlashBag.php
    answers:
        - {value: "The <info>FlashBag::add()</info> method allow to add a set of messages while <info>FlashBag::set()</info> allow to add a single message", correct: false}
        - {value: "The <info>FlashBag::add()</info> method allow to add a single message while <info>FlashBag::set()</info> allow to add a set of messages", correct: true}
        - {value: "The <info>FlashBag::add()</info> method allow to add a single message while <info>FlashBag::set()</info> allow to add a set of messages using a callback", correct: false}
        - {value: "They behave the same way", correct: false}
-
    question: "Could all <info>FlashBag</info> messages be overriden ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.1/src/Symfony/Component/HttpFoundation/Session/Flash/FlashBag.php#L127
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "What will be the result of invoking the <info>isXmlHttpRequest()</info> method on a <info>Symfony\\Component\\HttpFoundation\\Request</info> object ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/http-foundation/blob/5.3/Request.php#L1763
    answers:
        - {value: "<info>true</info> if the request has the <info>X-Requested-With</info> header set to <info>XMLHttpRequest</info>", correct: true}
        - {value: "<info>true</info> if the request contains XML elements", correct: false}
        - {value: "<info>true</info> if the request must generate an XML response", correct: false}
        - {value: "<info>true</info> if the request has the <info>Content-Type</info> header set to <info>application/xml</info>", correct: false}
-
    question: "How to access the <info>$_COOKIES</info> from the <info>Symfony\\Component\\HttpFoundation\\Request $request</info> object ?"
    code_snippet: ~
    correction_help:
        - http://symfony.com/doc/current/components/http_foundation.html#accessing-request-data
    answers:
        - {value: "$request->cookies", correct: true}
        - {value: "$request->cookie", correct: false}
        - {value: "$request->getCookies()", correct: false}
        - {value: "$request->getCookie()", correct: false}
        - {value: "$request->getCookieData()", correct: false}
-
    question: "Which method can be used to add a new value into <info>Session</info> ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.1/src/Symfony/Component/HttpFoundation/Session/Session.php#L93
    answers:
        - {value: "$session->insert()", correct: false}
        - {value: "$session->add()", correct: false}
        - {value: "$session->append()", correct: false}
        - {value: "$session->init()", correct: false}
        - {value: "$session->set()", correct: true}
-
    question: "Since <info>Symfony 6.0</info>, can a Response be created with <info>Response::create()</info> ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/Response.php#L223
        - https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/HttpFoundation/Response.php
    answers:
        - {value: "Yes", correct: false}
        - {value: "No", correct: true}