-
    question: "In which order does Symfony trigger the following events ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/HttpKernel/KernelEvents.php
    answers:
        - value: |
                1. kernel.request
                2. kernel.view
                3. kernel.controller
                4. kernel.response
                5. kernel.terminate
          correct: false
        - value: |
                1. kernel.request
                2. kernel.view
                3. kernel.controller
                4. kernel.terminate
                5. kernel.response
          correct: false
        - value: |
                1. kernel.request
                2. kernel.controller
                3. kernel.view
                4. kernel.response
                5. kernel.terminate
          correct: true
        - value: |
                1. kernel.request
                2. kernel.controller
                3. kernel.view
                4. kernel.terminate
                5. kernel.response
          correct: false
-
    question: "Could the build directory be overriden ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/5.2/reference/configuration/kernel.html#build-directory
        - https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/HttpKernel/Kernel.php#L337
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "What are the methods available in <info>Symfony\\Component\\HttpKernel\\Event\\KernelEvent</info> ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/HttpKernel/Event/KernelEvent.php
    answers:
        - {value: "getResponse", correct: false}
        - {value: "getKernel", correct: true}
        - {value: "getRequestType", correct: true}
        - {value: "isMainRequest", correct: true}
        - {value: "getException", correct: false}
        - {value: "hasResponse", correct: false}
        - {value: "hasRequest", correct: false}
        - {value: "getRequest", correct: true}
        - {value: "hasException", correct: false}
-
    question: "What is the aim of the <info>Symfony\\Component\\HttpKernel\\EventListener\\FragmentListener::onKernelRequest()</info> listener on <info>kernel.request</info> event ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/HttpKernel/EventListener/FragmentListener.php
    answers:
        - {value: "Handle as content fragments by this listener all URL paths starting with /_fragment", correct: true}
        - {value: "Handle as content all image, css, javascript that don't require security", correct: false}
        - {value: "Handle as content all files to let user download them", correct: false}
        - {value: "Handle as content all image, css, javascript that require security", correct: false}
-
    question: "What is the name of the special request attribute used by the <info>RouterListener</info> object to know which callable to invoke through the <info>HttpKernel</info> engine ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/2.8/components/http_kernel.html#1-the-kernel-request-event
    answers:
        - {value: "_action", correct: false}
        - {value: "_controller", correct: true}
        - {value: "_request", correct: false}
        - {value: "_route", correct: false}