-
    question: "Does the following configuration valid ?"
    code_snippet: |
        # config/packages/security.yaml
        security:
            # ...

            password_hashers:
                legacy:
                    algorithm: sha256
                    encode_as_base64: false
                    iterations: 1

                App\Entity\User:
                    algorithm: sodium
                    migrate_from:
                        - legacy

            # ...
    correction_help:
        - https://symfony.com/doc/5.3/security/passwords.html#configure-a-new-hasher-using-migrate-from
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}