-
    question: "What is the way to enable magic <info>__call</info> method ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/components/property_access/introduction.html#magic-call-method
    answers:
        - value: |
              $accessor = PropertyAccess::createPropertyAccessorBuilder()
                  ->getPropertyAccessor(true)
                ;
          correct: false
        - value: |
              $accessor = PropertyAccess::createPropertyAccessorBuilder()
                  ->enableMagicCall()
                  ->getPropertyAccessor()
                ;
          correct: true
        - value: |
              $accessor = PropertyAccess::createPropertyAccessor()
                  ->enableMagicCall()
                ;
          correct: false
        - value: |
              $accessor = PropertyAccess::createPropertyAccessor(true);
          correct: false
-
    question: "Is the <info>__call</info> feature enabled by default ?"
    code_snippet: ~
    correction_help:
        - http://symfony.com/doc/current/components/property_access/introduction.html#magic-call-method
    answers:
        - {value: "Yes", correct: false}
        - {value: "No", correct: true}