-
    question: "Could custom extractors be created ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/2.8/components/property_info.html#creating-your-own-extractors
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}