-
    question: "Considering the following code snippet, what will be the generated URL when calling <info>path('list')</info> from a Twig Template ?"
    code_snippet: |
        /**
         * @Route(
         *  "/blog/{!page}",
         *  name="list",
         *  requirements={"page": "\d+"},
         *  defaults={"page": 1}
         * )
         */
        public function list(int $page): Response
        {
            // ...
        }
    correction_help:
        - https://symfony.com/doc/current/routing.html#optional-parameters
    answers:
        - {value: "/blog/1", correct: true}
        - {value: "A <info>MissingMandatoryParametersException</info> will be raised", correct: false}
        - {value: "/blog/", correct: false}
        - {value: "/blog", correct: false}
-
    question: "Which exception is thrown when a <info>Route</info> with path <info>/page/{foo}/{foo}</info> cannot be compiled ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Routing/RouteCompiler.php#L39
    answers:
        - {value: "InvalidArgumentException", correct: false}
        - {value: "InvalidRouteCompilationContextException", correct: false}
        - {value: "RuntimeException", correct: false}
        - {value: "LogicException", correct: true}
        - {value: "RouteCompilationException", correct: false}
