-
    question: "What is the signature of the <info>voteOnAttribute()</info> method from <info>Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter</info> abstract class?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/current/security/voters.html#the-voter-interface
    answers:
        - {value: "voteOnAttribute(string $attribute, TokenInterface $token, mixed $subject)", correct: false}
        - {value: "voteOnAttribute(TokenInterface $token, string $attribute, mixed $subject)", correct: false}
        - {value: "voteOnAttribute(TokenInterface $token, mixed $subject, string $attribute)", correct: false}
        - {value: "voteOnAttribute(string $attribute, mixed $subject, TokenInterface $token)", correct: true}
-
    question: "What is the listener that handles security exceptions and when appropriate, helps the user to authenticate ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/2.0/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php
    answers:
        - {value: "Symfony\\Component\\Security\\Http\\Firewall\\AuthListener", correct: false}
        - {value: "Symfony\\Component\\Security\\Http\\Firewall\\SecurityListener", correct: false}
        - {value: "Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener", correct: true}
        - {value: "Symfony\\Component\\Security\\Http\\Firewall\\AuthenticationListener", correct: false}
-
    question: "Which sentences are true about user checkers ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/2.8/security/user_checkers.html
    answers:
        - {value: "User checkers must implement a <info>preCheck</info> method", correct: false}
        - {value: "User checker methods throw an exception when requirements are not fulfilled", correct: true}
        - {value: "User checkers must implement a <info>preAuth</info> method", correct: false}
        - {value: "User checkers must implement a <info>check</info> method", correct: false}
        - {value: "User checker methods returns false when requirements are not fulfilled", correct: false}
        - {value: "User checkers must implement a <info>checkPreAuth</info> method", correct: true}
-
    question: "When configuring the main firewall of an application, could its <info>check_path</info> route be covered by another firewall ?"
    code_snippet: ~
    correction_help:
        - http://symfony.com/doc/current/reference/configuration/security.html#check-path
    answers:
        - {value: "Yes", correct: false}
        - {value: "No", correct: true}