-
    question: "Is the following code valid ?"
    code_snippet: |
        #[Serializer\Context(
            normalizationContext: [DateTimeNormalizer::FORMAT_KEY => \DateTime::RFC3339],
            groups: ['extended']
        )]
        public \DateTime $date;
    correction_help:
        - http://...
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "Could interface and/or abstract classes be serialized ?"
    code_snippet: ~
    correction_help:
        - https://symfony.com/doc/4.1/components/serializer.html#serializing-interfaces-and-abstract-classes
        - https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Serializer/Mapping/ClassDiscriminatorResolverInterface.php
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}