-
    question: "Could attributes be skipped when initializing a lazy object ?"
    code_snippet: ~
    correction_help:
        - https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/VarExporter/LazyGhostTrait.php#L23
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}