-
    question: "Is the following code valid ?"
    code_snippet: |
        <?php

        use Symfony\Component\Yaml\Yaml;

        $value = Yaml::parse(file_get_contents('/path/to/file.yml'));
    correction_help:
        - https://symfony.com/doc/current/components/yaml/introduction.html#reading-yaml-files
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}