-
    question: "Which internal method is called when using the <info>deprecated</info> tag ?"
    code_snippet: ~
    correction_help:
        - https://twig.symfony.com/doc/1.x/tags/deprecated.html
    answers:
        - {value: "<info>trigger_error()</info>", correct: true}
        - {value: "<info>sprintf</info>", correct: false}
        - {value: "<info>user_error()</info>", correct: false}
        - {value: "<info>error_log()</info>", correct: false}
-
    question: "What is the output of the following code snippet ?"
    code_snippet: |
        {% for i in range(1, 10, 2) %}
            {{ i }}{% if not loop.last %},{% endif %}
        {% endfor %}
    correction_help:
        - https://twig.symfony.com/doc/functions/range.html
    answers:
        - {value: "1,2,3,4,5,6,7,8,9,10", correct: false}
        - {value: "1,10,1,10", correct: false}
        - {value: "1,3,5,7,9", correct: true}
        - {value: "2,4,6,8,10", correct: false}
-
    question: "Which expression can be applied to <info>???</info> in order to display the name of each people along with his name and age ?"
    code_snippet: |
        {% set people = [
            {firstname: "Bob", lastname: "Smith", age: 12},
            {firstname: "Alice", lastname: "Dupond", age: 13},
        ] %}

        {{ ??? }} {# Must display "Bob Smith is 12 years old, Alice Dupond is 13 years old" #}
    correction_help:
        - https://twig.symfony.com/doc/1.x/filters/map.html
        - https://twig.symfony.com/doc/1.x/filters/join.html
        - https://twig.symfony.com/doc/1.x/filters/split.html
    answers:
        - {value: "{{ people|map(p => \"#{p.firstname} #{p.lastname} is #{p.age} years old\") }}", correct: true}
        - {value: "None of those", correct: false}
        - {value: "{{ people|split(', ') }}", correct: false}
        - {value: "{{ people|join(', ') }}", correct: false}
-
    question: "Given the case where the opcache/APC cache for template need to be invalidated, is the following code valid ?"
    code_snippet: |
        <?php

        // ...

        $twig = new Environment($loader, [
            'cache' => new FilesystemCache('/some/cache/path', FilesystemCache::FORCE_BYTECODE_INVALIDATION),
            // ...
        ]);
    correction_help:
        - https://twig.symfony.com/doc/1.x/recipes.html#refreshing-modified-templates-when-opcache-or-apc-is-enabled
    answers:
        - {value: "Yes", correct: true}
        - {value: "No", correct: false}
-
    question: "Given a template where an object <info>Foo</info> is passed and the following call <info>{{ foo.bar }}</info>, what is the first test done by Twig ?"
    code_snippet: ~
    correction_help:
        - https://twig.symfony.com/doc/1.x/templates.html#variables
    answers:
        - {value: "If <info>Foo</info> is an object and <info>bar</info> a property", correct: false}
        - {value: "If <info>Foo</info> is an array and <info>bar</info> a valid element", correct: true}
        - {value: "If <info>Foo</info> is an object and <info>bar</info> a valid method (or the constructor)", correct: false}
        - {value: "If <info>Foo</info> is an object and <info>bar</info> is an isser (<info>isBar</info>)", correct: false}
-
    question: "Consider the following Twig code snippet, what will be the result of evaluating this Twig template ?"
    code_snippet: |
        {% extends 'layout.html.twig' %}

        {% block title 'Hello World!' %}

        My name is Amanda.
    correction_help:
        - https://twig.symfony.com/doc/tags/extends.html
    answers:
        - {value: "The template is successfully evaluated", correct: false}
        - {value: "Twig will raise a <info>Twig_Error_Syntax</info> exception and the template will not be evaluated", correct: true}
-
    question: "Which syntax is valid to avoid escaping ?"
    code_snippet: ~
    correction_help:
        - https://twig.symfony.com/doc/1.x/filters/escape.html
    answers:
        - {value: "{{ hello|no_escape }}", correct: false}
        - {value: "{{ hello|raw }}", correct: true}
        - {value: "{{ hello }}", correct: false}
        - {value: "{{ hello|escape('no') }}", correct: false}
-
    question: "Considering the following Twig code snippet, what will be the result of evaluating this template without passing it the <info>color</info> variable when the <info>strict_variables</info> global setting is off ?"
    code_snippet: |
        The {{ color }} car!
    correction_help:
        - https://twig.symfony.com/doc/1.x/templates.html#variables
        - https://twig.symfony.com/doc/2.x/templates.html#variables
        - https://twig.symfony.com/doc/2.x/api.html#environment-options
        - https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Extension/Core.php#L1447-L1479
    answers:
        - {value: "The template will be partially evaluated and the string <info>The</info> will be displayed in the web browser", correct: false}
        - {value: "The template will be successfully evaluated and the string <info>The empty car!</info> will be displayed in the web browser", correct: false}
        - {value: "Twig will raise a <info>Twig_Error_Runtime</info> exception preventing the template from being evaluated", correct: false}
        - {value: "The template will be partially evaluated and the string <info>The car!</info> will be displayed in the web browser", correct: true}
-
    question: "What is the correct value to display the value of a PHP constant in Twig ?"
    code_snippet: ~
    correction_help:
        - https://twig.symfony.com/doc/functions/constant.html
    answers:
        - {value: "{{ Namespace\\ClassName::CONSTANT_NAME }}", correct: false}
        - {value: "{{ constant(Namespace\\ClassName::CONSTANT_NAME) }}", correct: false}
        - {value: "{{ constant(Namespace\\\\ClassName::CONSTANT_NAME }}", correct: true}
        - {value: "{{ Namespace\\\\ClassName::CONSTANT_NAME }}", correct: false}
-
    question: "When writing a <info>Twig_Test</info>, what is a <info>node_class</info> for ?"
    code_snippet: ~
    correction_help:
        - https://twig.symfony.com/doc/2.x/advanced.html#tests
    answers:
        - {value: "The given test will use a semantic validation in addition to the basic evaluation", correct: false}
        - {value: "The given test will be compiled into PHP primitives", correct: true}
        - {value: "The <info>node_class</info> is a mandatory option to get defined in a <info>Twig_Environment</info>", correct: false}
        - {value: "The given test will rely on a custom <info>Twig_NodeVisitorInterface</info>", correct: false}
-
    question: "Which of the following is not a supported Twig tag ?"
    code_snippet: ~
    correction_help:
        - https://twig.symfony.com/documentation
    answers:
        - {value: "while", correct: true}
        - {value: "include", correct: false}
        - {value: "for", correct: false}
        - {value: "do", correct: false}
        - {value: "embed", correct: false}
-
    question: "Which of the following operators has the lowest precedence ?"
    code_snippet: ~
    correction_help:
        - https://twig.symfony.com/doc/3.x/templates.html#expressions
    answers:
        - {value: "and", correct: true}
        - {value: "!=", correct: true}
        - {value: ">=", correct: true}
        - {value: "==", correct: true}