-
    question: "Considering the following code snippet, which of the following <info>$letters</info> variable declarations will make this script generate an HTML list of the 26 alphabet letters on any PHP versions ?"
    code_snippet: |
        <ul>
            <?php foreach ($letters as $letter) : ?>
                <li><?= $letter ?></li>
            <?php endforeach ?>
        </ul>
    correction_help:
        - http://php.net/manual/en/function.range.php
        - http://php.net/manual/en/function.explode.php
        - http://php.net/manual/en/function.str-split.php
    answers:
        - {value: "$letters = str_split('ABCDEFGHIJKLMNOPQRSTUVWXYZ');", correct: true}
        - {value: "$letters = explode('', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ');", correct: true}
        - {value: "$letters = range('A', 'Z');", correct: true, code_snippet: true}
        - {value: "$letters = split('//', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ');", correct: false}
        - {value: "$letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';", correct: false}
-
    question: "Considering the following code snippet, which statement should replace the <info>????</info> placeholder in order to make this code snippet output the string <info>private</info> ?"
    code_snippet: |
        <?php

            class Bar
            {
                private $foo = 'private';
            }

            function getter()
            {
                return function() {
                    return $this->foo;
                };
            }

            ????
    correction_help:
        - https://php.net/manual/en/class.closure.php
    answers:
        - {value: "echo getter()->bindTo(new Bar(), 'Bar')();", correct: true}
        - {value: "echo getter()->bindTo(new Bar())();", correct: false}
        - {value: "echo getter()->bindTo('Bar', 'Bar')();", correct: false}
        - {value: "echo getter()->bindTo(new Bar(), new Bar())();", correct: true}
        - {value: "This is not possible", correct: false}

