-
    question: "What PSRs correspond to autoloading standards ?"
    code_snippet: ~
    correction_help:
        - https://www.php-fig.org/psr/
    answers:
        - {value: "PSR-0", correct: true}
        - {value: "PSR-1", correct: false}
        - {value: "PSR-2", correct: false}
        - {value: "PSR-3", correct: false}
        - {value: "PSR-4", correct: true}
        - {value: "PSR-5", correct: false}
        - {value: "PSR-6", correct: false}
        - {value: "PSR-7", correct: false}
-
    question: "What is PSR-3 ?"
    code_snippet: ~
    correction_help:
        - https://www.php-fig.org/psr/psr-3/
    answers:
        - {value: "A common logging interface", correct: true}
        - {value: "A coding style guide", correct: false}
        - {value: "A utility to convert non-namespaced PHP classes into namespaced ones", correct: false}
        - {value: "A standard way to convert fully qualified names into file paths", correct: false}